blogger_oauth_server_api:
    resource: "@BloggerOAuthServerBundle/Resources/config/routing_api.yml"
    prefix:   /api/oauth/v2

blogger_oauth_server_auth:
    resource: "@BloggerOAuthServerBundle/Resources/config/routing_authorize.yml"
    prefix:   /

blogger_test:
    resource: "@BloggerTestBundle/Resources/config/routing.yml"
    prefix:   /

blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /oauth_login

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

login:
    path:  /login
    defaults: { _controller: BloggerBlogBundle:Security:login }
    requirements:
      _method: GET|POST

login_check:
    path:  /login_check

logout:
    path:  /logout

qq_login:
    pattern: /login/check_qq

weibo_login:
    pattern: /login/check_weibo
